### ISSUE TITLE
Unhandled special case in Game.takeCardFromRevealed

### ISSUE THREAD

**Issue by v4m3rrr** [Splendor-Mobile-Game/ServerSide#114]
In the `Game` class, we have a function called `takeCardFromRevealed`. In this function, we do not handle the possibility that the `getRandomCard` function can return `null`.

https://github.com/Splendor-Mobile-Game/ServerSide/blob/aa71732c03bc0c199c53b518a108197a37dd537f/src/main/java/com/github/splendor_mobile_game/game/model/Game.java#L53-L61

Also on that function rely `BuyRevealedMine` reaction which does not handle a drawn card being `null`. My suggestion is that the server should send two announcements: one with the buyer and information on whether a new card was drawn, and the second only sent when a new card was drawn with detailed information about it.
https://github.com/Splendor-Mobile-Game/ServerSide/blob/aa71732c03bc0c199c53b518a108197a37dd537f/src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/BuyRevealedMine.java#L198-L250
https://github.com/Splendor-Mobile-Game/ServerSide/blob/aa71732c03bc0c199c53b518a108197a37dd537f/src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/BuyRevealedMine.java#L52-L82

**Comment by kestivvi** [comment]
Very good, I agree 🧃
