### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ServerSide#146]
**Class diagram is required to complete project.**

To successfully complete this project, we need to create a detailed class diagram that accurately represents the business logic. So, the class diagram should only include the game and database packages. As we develop the class diagram, we may encounter design flaws or inconsistencies that require us to refactor our code.

I have heard that IntelliJ or other software has tools that allows the creation of a class diagram from the code. This feature can speed up the process significantly, especially if there are any changes to the structure in the future.

**Comment by Vertonowsky** [comment]
I created a class diagram which contains business login classes. Result is shown below:

![model](https://github.com/Splendor-Mobile-Game/ServerSide/assets/27568559/5ed89753-05a3-4109-bf96-58953da93d40)
