### ISSUE TITLE
Optional and required fields in data classes for reactions

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ServerSide#19]
We can improve data classes (`@DataClass` annotation) with another annotation like `@Optional` which could be used on fields in data classes and that would mean that this field is optional, user is not obligated to provide it and if this field is not provided it can be null. On the other hand, fields that aren't annotated with `@Optional` would be required and if user doesn't provide them they would got an error response with appropriate message that this field is required.

**Comment by Vertonowsky** [comment]
It has no usage. Fields are separate for different reactions. If you don't need them - don't create them.

**Comment by kestivvi** [comment]
Seems reasonable, ok then.
