### ISSUE TITLE
New labels

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ServerSide#20]
I propose adding new labels for our issues and pull requests. I've got an inspiration from [this site](https://seantrane.com/posts/logical-colorful-github-labels-18230/).

# Effort labels
Describes the relative effort to complete an issue or pull request.

Increasing fibonacci sequence from 1 to 13. Meaning is that, solving issue or pr with effort ie. 5 is taking that amount of effort what solving one issue with effort: 3 and one with effort: 2. So every next level is taking such amount of effort what 2 previous levels combined. That's obvious, but I have to write it down. Of course it's not absolute scale, it is relative, because every programmer has different sense of effort. What something is easy for one programmer is hard for the other one.

- effort: 1
- effort: 2
- effort: 3
- effort: 5
- effort: 8
- effort: 13

# Type labels
Just type of thing being discussed or worked on.

- type: bug (issue: reporting a bug)
- type: fix (pull request: fixing a bug)
- type: feature (or enhancement, new functionality)
- type: refactor (no change in functionality, but in mechanizm under the hood, improving performance or security)
- type: chore (like updating dependencies, changing imports, moving files)
- type: discussion (just discussion, brain storming)
- type: docs
- type: security
- type: testing

# Priority labels
Focused on describing the immediacy of attention required.

- priority: now
- priority: 2 days
- priority: this week

If deadline is above a week, I think there is no reason to attach a label for that. It's just no priority to do that thing.

I'm open for a discussion about the labels and changing my proposal if you have other good ideas.

**Comment by kestivvi** [comment]
Additionally I would add following labels

# Scope
Defining who's job it is.

- scope: testers
- scope: developers

# Other
- networking (Issue related to multiplayer and websockets)
- admin needed

**Comment by kestivvi** [comment]
Let's do also the state labels:

- state: duplicate (This issue or pull request already exists)
- state: help wanted (Extra attention is needed by someone who knows this stuff)
- state: need more info (Insufficient information to resolve this issue)
- state: wontfix (This will not be worked on)

**Comment by Antonidass5** [comment]
Hey, @kestivvi it's ok?

**Comment by kestivvi** [comment]
Yeah, almost. Change the current label `enhancement` to `type: feature`, please.

**Comment by Antonidass5** [comment]
Done @kestivvi

**Comment by kestivvi** [comment]
Good job! Solved. I'm closing the issue.
