### ISSUE TITLE
Data classes for responses in reaction

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ServerSide#21]
We have data classes that define what client has to send. Its second purpose is that it's parsed from json to object automatically. Wouldn't it be nice to have such classes for responses as well? No more formatting to json, it'd be done automatically by the framework.

It's just asking for the opinion, do you want something like that? Would it be more comfortable or not really?

**Comment by kestivvi** [comment]
I've created draft pull request so that you can better see what I mean.

**Comment by Vertonowsky** [comment]
Let's focus on expanding our application. If it comes handy after adding complete communication between client and Server (at least untill game is started) then we will add that.
