### ISSUE TITLE
Get random card from database

### ISSUE THREAD

**Issue by Vertonowsky** [Splendor-Mobile-Game/ServerSide#26]
### We are going to work on /game/model/Game.java file. 
There is already implemented `getRandomCards(ArrayList<Card> cardList, int amount)` function which picks **amount** of random cards from supplied ArrayList. 

Picked cards are unique. You can't pick **amount** of cards with duplicates.

## Problem description

Application needs a function to uncover a random card from ALL CARDS (you will get them from InMemoryDatabase) but you can't uncover a single card multiple times. If it was picked once, then probably it is already laying on the table or player bought this.
Current function doesn't support that.

## Fix

Modify getRandomCards() to pick only one random card, but check if it was picked ever before (local static Arraylist would be a good solution). If all cards were picked before (database should contain 40 cards) then return null.

**Comment by kestivvi** [comment]
It's done. Closing.
