### ISSUE TITLE
Player name uniqueness

### ISSUE THREAD

**Issue by Vertonowsky** [Splendor-Mobile-Game/ServerSide#30]
## Problem description
Every player is identified by his uuid + name. Both must be unique. 

If we want to allow users from different rooms to have the same name, then we have to implement that.
Right now only one user across whole application can have specific name.

**Comment by kestivvi** [comment]
Yeah, that's pretty disappointing that you cannot name yourself "Krzysztof", because there is guy in other room that you don't have been even aware of him and he had named himself "Krzysztof" before you.
